[versions]

kotlin = "2.3.10"
androidGradlePlugin = "9.1.0"
firebaseBom = "34.12.0"
anrWatchDog = "1.4.0"
kermit = "2.1.0"

[libraries]
# COMMON
common-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
common-kermitCrashlytics = { module = "co.touchlab:kermit-crashlytics", version.ref = "kermit" }

# ANDROID
android-firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
android-firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics" }
android-anrWatchDog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrWatchDog" }

[plugins]

kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
